name: CI/CD to Azure Container Registry kishan.azurecr.io

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  AZURE_CONTAINER_REGISTRY: kishan.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: kishan
  IMAGE_NAME: webapp

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Run Maven build
      run: |
        mvn --batch-mode --update-snapshots verify

    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: target/${{ env.IMAGE_NAME }}-0.0.1-SNAPSHOT.jar

    # Install Podman (important)
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman

    # Login to ACR using Podman
    - name: Login to Azure Container Registry
      run: |
        podman login ${{ env.AZURE_CONTAINER_REGISTRY }} \
          --username ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }} \
          --password ${{ secrets.WEBAPPSECRET }}

    #  Build Image
    - name: Build Image
      run: |
        podman build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
                     -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    #  Push Image
    - name: Push Image
      run: |
        podman push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        podman push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest